/**
 * Engram — Job Archive Page
 * Self-contained script for the standalone archive extension page.
 */
(function () {
  'use strict';

  // ── Browser API / Storage ────────────────────────────────────────────────────

  var _api = (typeof browser !== 'undefined') ? browser : chrome;

  function storageGet(key) {
    return new Promise(function (resolve) {
      _api.storage.local.get(key, function (r) { resolve(r || {}); });
    });
  }

  function storageSet(obj) {
    return new Promise(function (resolve) {
      _api.storage.local.set(obj, resolve);
    });
  }

  // ── Package builders ────────────────────────────────────────────────────────

  function buildMultiJobPrompt(jobs) {
    var jobList = jobs.map(function (j, i) {
      var jobUrl = j.canonicalUrl || j.url || 'Unknown';
      return [
        '### Job ' + (i + 1) + ': ' + (j.title || 'Unknown') + ' at ' + (j.company || 'Unknown'),
        '',
        '- **Location:** ' + (j.location || 'Unknown'),
        '- **Remote Status:** ' + (j.remoteStatus || 'Not specified'),
        '- **Salary:** ' + (j.salary || 'Not disclosed'),
        '- **URL:** ' + jobUrl,
        '',
        '**Description:**',
        '',
        j.description ? j.description.slice(0, 2000) : 'No description captured.',
      ].join('\n');
    }).join('\n\n---\n\n');

    return '# LinkedIn Job Search Analysis\n\n' +
      'I collected these LinkedIn jobs. Please compare the selected roles, identify strongest fit, ' +
      'check red flags, map requirements to my skills/projects, suggest resume positioning, ' +
      'and prepare application next steps.\n\n' +
      'Specifically provide:\n\n' +
      '1. **Ranking by overall fit** — Which roles are the strongest candidates?\n' +
      '2. **Red flags** — Any signs of scam, misleading requirements, or unrealistic expectations?\n' +
      '3. **Requirements mapping** — What skills and experience do these roles require?\n' +
      '4. **Resume positioning** — How should I position myself for each role?\n' +
      '5. **Application next steps** — Which jobs to prioritize and what to research before applying?\n' +
      '6. **Questions to ask recruiters** — What should I clarify for each role?\n\n' +
      '---\n\n' + jobList + '\n\n---\n' +
      '_Generated by Engram \xb7 ' + new Date().toLocaleString() + '_\n';
  }

  function buildJobsMd(jobs) {
    var lines = [
      '# Saved Jobs', '',
      '_' + jobs.length + ' job(s) \xb7 Generated by Engram \xb7 ' + new Date().toISOString() + '_',
      '',
    ];
    jobs.forEach(function (j, i) {
      lines.push('## ' + (i + 1) + '. ' + (j.title || 'Unknown') + ' — ' + (j.company || 'Unknown'));
      lines.push('');
      if (j.location)     lines.push('- **Location:** ' + j.location);
      if (j.remoteStatus) lines.push('- **Remote:** ' + j.remoteStatus);
      if (j.salary)       lines.push('- **Salary:** ' + j.salary);
      var jobUrl = j.canonicalUrl || j.url;
      if (jobUrl)         lines.push('- **URL:** ' + jobUrl);
      if (j.description)  lines.push('', '**Description:**', '', j.description.slice(0, 2000));
      lines.push('', '---', '');
    });
    return lines.join('\n');
  }

  function buildJobSearchHandoff(jobs) {
    var summary = jobs.map(function (j, i) {
      var jobUrl = j.canonicalUrl || j.url || '';
      return (i + 1) + '. **' + (j.title || 'Unknown') + '** at **' + (j.company || 'Unknown') +
        '** — ' + (j.location || 'Unknown') + ' (' + (j.remoteStatus || 'N/A') + ')' +
        (jobUrl ? ' — ' + jobUrl : '');
    }).join('\n');

    return '# Job Search Handoff\n\n' +
      '> Generated by Engram. Use this to continue your job search analysis in a new AI chat.\n\n' +
      '## Saved Jobs Summary\n\n' + summary + '\n\n' +
      '## How to Use\n\n' +
      '1. Start a new chat in ChatGPT or Claude.ai.\n' +
      '2. Paste the prompt from `ai-prompt.md` to begin the analysis.\n' +
      '3. Reference `jobs.md` for full job details.\n' +
      '4. Use `jobs.json` if you need machine-readable data.\n\n' +
      '_Generated: ' + new Date().toISOString() + '_\n';
  }

  // ── Avatar helper ───────────────────────────────────────────────────────────

  function getInitials(company) {
    if (!company) return '?';
    var words = company.trim().split(/\s+/).filter(Boolean);
    if (words.length === 1) return words[0].slice(0, 2).toUpperCase();
    return (words[0][0] + words[words.length - 1][0]).toUpperCase();
  }

  function fillAvatar(avEl, job) {
    avEl.innerHTML = '';
    var logoUrl  = job.companyLogoUrl;
    var initials = job.companyInitials || getInitials(job.company);
    if (logoUrl) {
      var img = document.createElement('img');
      img.src = logoUrl;
      img.onerror = function () { this.remove(); avEl.textContent = initials; };
      avEl.appendChild(img);
    } else {
      avEl.textContent = initials;
    }
  }

  // ── State ───────────────────────────────────────────────────────────────────

  var allJobs = [];

  // ── Render ──────────────────────────────────────────────────────────────────

  function renderJobs() {
    var list  = document.getElementById('jobList');
    var wrap  = document.getElementById('jobListWrap');
    var empty = document.getElementById('emptyState');
    var count = document.getElementById('headerCount');

    if (!list) return;
    list.innerHTML = '';

    var n = allJobs.length;
    if (count) count.textContent = n + ' saved';

    if (!n) {
      if (wrap)  wrap.style.display  = 'none';
      if (empty) empty.style.display = '';
      return;
    }

    if (wrap)  wrap.style.display  = '';
    if (empty) empty.style.display = 'none';

    allJobs.forEach(function (job) {
      var row = document.createElement('div');
      row.className = 'job-row';
      row.dataset.jobId = job.id;

      // Checkbox (queued = include in package)
      var cb = document.createElement('input');
      cb.type      = 'checkbox';
      cb.className = 'job-check';
      cb.checked   = job.queued !== false;
      cb.title     = cb.checked ? 'Included in package' : 'Excluded from package';
      cb.addEventListener('change', function () { toggleQueued(job.id, cb.checked); });

      // Avatar
      var av = document.createElement('div');
      av.className = 'job-avatar';
      fillAvatar(av, job);

      // Info
      var info = document.createElement('div');
      info.className = 'job-info';

      var titleEl = document.createElement('div');
      titleEl.className   = 'job-title';
      titleEl.textContent = job.title || 'Unknown title';

      var companyEl = document.createElement('div');
      companyEl.className   = 'job-company';
      companyEl.textContent = job.company || '';

      var locationParts = [
        job.location,
        (job.remoteStatus && job.remoteStatus !== 'Not specified') ? job.remoteStatus : '',
      ].filter(Boolean);

      var locationEl = document.createElement('div');
      locationEl.className   = 'job-location';
      locationEl.textContent = locationParts.join(' \xb7 ');

      info.appendChild(titleEl);
      if (job.company)        info.appendChild(companyEl);
      if (locationParts.length) info.appendChild(locationEl);

      var linkUrl = job.canonicalUrl || job.url;
      if (linkUrl) {
        var linkEl = document.createElement('a');
        linkEl.className = 'job-link';
        linkEl.href      = linkUrl;
        linkEl.target    = '_blank';
        linkEl.rel       = 'noopener noreferrer';
        linkEl.textContent = linkUrl;
        info.appendChild(linkEl);
      }

      // Delete
      var del = document.createElement('button');
      del.className   = 'job-delete';
      del.textContent = '✕';
      del.title       = 'Delete job';
      del.addEventListener('click', function () { removeJob(job.id, row); });

      row.appendChild(cb);
      row.appendChild(av);
      row.appendChild(info);
      row.appendChild(del);
      list.appendChild(row);
    });
  }

  // ── Data operations ─────────────────────────────────────────────────────────

  async function toggleQueued(jobId, queued) {
    var idx = allJobs.findIndex(function (j) { return j.id === jobId; });
    if (idx !== -1) {
      allJobs[idx].queued = queued;
      await storageSet({ engramSavedJobs: allJobs });
      refreshQueuedBadge();
    }
  }

  async function removeJob(jobId, rowEl) {
    allJobs = allJobs.filter(function (j) { return j.id !== jobId; });
    await storageSet({ engramSavedJobs: allJobs });
    if (rowEl && rowEl.parentNode) rowEl.remove();
    var count = document.getElementById('headerCount');
    if (count) count.textContent = allJobs.length + ' saved';
    var wrap  = document.getElementById('jobListWrap');
    var empty = document.getElementById('emptyState');
    if (!allJobs.length) {
      if (wrap)  wrap.style.display  = 'none';
      if (empty) empty.style.display = '';
    }
    refreshQueuedBadge();
  }

  async function selectAll() {
    allJobs.forEach(function (j) { j.queued = true; });
    await storageSet({ engramSavedJobs: allJobs });
    renderJobs();
    refreshQueuedBadge();
  }

  async function deselectAll() {
    allJobs.forEach(function (j) { j.queued = false; });
    await storageSet({ engramSavedJobs: allJobs });
    renderJobs();
    refreshQueuedBadge();
  }

  function refreshQueuedBadge() {
    var el = document.getElementById('queuedCount');
    if (!el) return;
    var q = allJobs.filter(function (j) { return j.queued !== false; }).length;
    el.textContent = q + ' queued';
  }

  // ── Package builder ─────────────────────────────────────────────────────────

  async function buildPackage() {
    var bar  = document.getElementById('statusBar');
    var jobs = allJobs.filter(function (j) { return j.queued !== false; });

    if (!allJobs.length) {
      setStatus(bar, 'No saved jobs. Use the widget on LinkedIn pages.', '');
      return;
    }
    if (!jobs.length) {
      setStatus(bar, 'Select at least one saved job for the package.', '#f59e0b');
      return;
    }

    setStatus(bar, 'Building package…', '');

    try {
      var datestamp = new Date().toISOString().slice(0, 10);
      var zip = new window.ZipWriter();
      zip.addText('job-search-handoff.md', buildJobSearchHandoff(jobs));
      zip.addText('jobs.md',               buildJobsMd(jobs));
      zip.addText('jobs.json',             JSON.stringify(jobs, null, 2));
      zip.addText('ai-prompt.md',          buildMultiJobPrompt(jobs));

      var blob = zip.build();
      var url  = URL.createObjectURL(blob);
      var a    = document.createElement('a');
      a.href     = url;
      a.download = 'engram-job-package-' + datestamp + '.zip';
      a.click();
      URL.revokeObjectURL(url);

      setStatus(bar, '✓ Job package downloaded (' + jobs.length + ' jobs)', '#22c55e');
    } catch (e) {
      console.error('[Engram] archive package build failed', e);
      setStatus(bar, 'Package build failed', '#ef4444');
    }
  }

  function setStatus(el, text, color) {
    if (!el) return;
    el.textContent = text;
    el.style.color = color || '';
  }

  // ── Init: load jobs + logo cache, backfill, render ──────────────────────────

  async function init() {
    var stored = await storageGet(['engramSavedJobs', 'engramCompanyLogoCache']);
    allJobs = (stored && stored.engramSavedJobs) || [];
    var logoCache = (stored && stored.engramCompanyLogoCache) || {};

    // Backfill companyLogoUrl from cache for jobs that are missing it
    var needsPersist = false;
    allJobs.forEach(function (job) {
      if (!job.companyLogoUrl && job.company) {
        var key    = job.company.toLowerCase().trim();
        var cached = logoCache[key];
        if (cached && cached.companyLogoUrl) {
          job.companyLogoUrl = cached.companyLogoUrl;
          if (!job.companyInitials && cached.companyInitials) {
            job.companyInitials = cached.companyInitials;
          }
          needsPersist = true;
        }
      }
    });

    if (needsPersist) {
      try { await storageSet({ engramSavedJobs: allJobs }); } catch (_) {}
    }

    renderJobs();
    refreshQueuedBadge();
  }

  // ── Event listeners ─────────────────────────────────────────────────────────

  document.getElementById('btnSelectAll').addEventListener('click', selectAll);
  document.getElementById('btnDeselectAll').addEventListener('click', deselectAll);
  document.getElementById('btnBuildPackage').addEventListener('click', buildPackage);

  init();

})();
